sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 'stable'
  - '6'
  - '4'
  - '0.10'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  # detect if the current build's node version is < 4
  # if yes, only run tests
  # if not, run complete validation script
  - if [[ `node -v | sed 's/[^0-9\.]//g'` < 4 ]]; then npm run cover; else npm run validate; fi
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run report-coverage
  - npm run semantic-release
branches:
  only:
    - master
